### ISSUE TITLE
store face

### ISSUE THREAD

**Issue by jcontratto** [alycapps/Team2#11]
- [x] make cards with store name

- [x] onclick expand files

**Comment by nlee728** [comment]
COPYING NOTES FROM SLACK

HTML PAGES
/login --- login page
(will use login.html)
/signup – signup page
(will use signup.html)
/store (used to be called /members) – your personal store where you see everything in your current stock and can add, delete and edit their own stuff (there is a buy button that will show all items for sale) 
(will use store.html)
/profile --- where members can add personal info like bio
(will use profile.html)
